// flow-typed signature: d03b236dc049d919f538e2a47af84ed7
// flow-typed version: <<STUB>>/fast-crc32c_v^2.0.0/flow_v0.108.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fast-crc32c'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fast-crc32c' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fast-crc32c/impls/js_crc32c' {
  declare module.exports: any;
}

declare module 'fast-crc32c/impls/sse4_crc32c' {
  declare module.exports: any;
}

declare module 'fast-crc32c/loader' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fast-crc32c/impls/js_crc32c.js' {
  declare module.exports: $Exports<'fast-crc32c/impls/js_crc32c'>;
}
declare module 'fast-crc32c/impls/sse4_crc32c.js' {
  declare module.exports: $Exports<'fast-crc32c/impls/sse4_crc32c'>;
}
declare module 'fast-crc32c/loader.js' {
  declare module.exports: $Exports<'fast-crc32c/loader'>;
}
