#!/usr/bin/env python3
import unittest
from decode_jwt_payload import handle_input_line

class TestHandleJwtInput(unittest.TestCase):
    def test_decode_token(self):
        # This fixture has been scientifically generated by uploading a data
        # with content "aaaa" with the JWT secret set to "secret".
        fixture = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm9maWxlVG9rZW4iOiI3MGM4ODFkNGEyNjk4NGRkY2U3OTVmNmY3MTgxN2M5Y2Y0NDgwZTc5IiwiaWF0IjoxNTc5OTY4OTU5fQ.MqKan9jXOZ9B4GWSDzzyO2YfSAetGuLOb1bq8dX2PEY"
        expected = "70c881d4a26984ddce795f6f71817c9cf4480e79"
        result = handle_input_line(fixture)
        self.assertEqual(result, expected)

if __name__ == '__main__':
    unittest.main()
